name: NoCheat

author: Evenprime

main: cc.co.evenprime.bukkit.nocheat.NoCheat
version: 2.09

commands:
  nocheat:
    description: NoCheat command(s)
    usage: |
           /<command> permlist player [permission] - to list the NoCheat relevant permissions of the player, optionally only those starting with [permission]
           /<command> reload - to reload NoCheats configuration file(s), without reloading the plugin itself

permissions:

  nocheat.*:
    description: Allow a player to bypass all checks and give him all admin permissions
    children:
      nocheat.checks.*: true
      nocheat.admin.*: true

  nocheat.checks.*:
    description: Allow the player to bypass all checks
    children:
      nocheat.checks.moving.*: true
      nocheat.checks.blockbreak.*: true
      nocheat.checks.blockplace.*: true
      nocheat.checks.interact.*: true
      nocheat.checks.fight.*: true
      nocheat.checks.chat.*: true
      nocheat.checks.timed.*: true

  nocheat.checks.moving.*:
    description: Allow the player to bypass all moving checks
    children:
      nocheat.checks.moving.flying: true
      nocheat.checks.moving.runfly: true
      nocheat.checks.moving.swimming: true
      nocheat.checks.moving.sneaking: true
      nocheat.checks.moving.noclip: true
      nocheat.checks.moving.morepackets: true
      nocheat.checks.moving.nofall: true
      
  nocheat.checks.fight.*:
    description: Allow the player to bypass all moving checks
    children:
      nocheat.checks.moving.direction: true
      nocheat.checks.moving.selfhit: true
      nocheat.checks.moving.noswing: true
      
  nocheat.checks.chat.*:
    description: Allow the player to bypass all moving checks
    children:
      nocheat.checks.moving.spam: true
      
  nocheat.checks.timed.*:
    description: Allow the player to bypass all moving checks
    children:
      nocheat.checks.moving.godmode: true
      
  nocheat.checks.blockbreak.*:
    description: Allow the player to bypass all blockbreak checks
    children:
      nocheat.checks.blockbreak.reach: true
      nocheat.checks.blockbreak.direction: true
      nocheat.checks.blockbreak.noswing: true
      
  nocheat.checks.blockplace.*:
    description: Allow the player to bypass all blockplace checks
    children:
      nocheat.checks.blockplace.reach: true
      nocheat.checks.blockplace.onliquid: true
      nocheat.checks.blockplace.noswing: true

  nocheat.checks.interact.*:
    description: Allow the player to bypass all interact checks
    children:
      nocheat.checks.interact.durability: true

  nocheat.checks.moving.flying:
    description: Allow a player to move free through the air (if given, the "running" check will be ignored anyway)
    default: op
  nocheat.checks.moving.runfly:
    description: Allow a player to move free, only limited by the flying check, if active (implicitly deactivates the "swimming" and "sneaking" check)
    default: op
  nocheat.checks.moving.swimming:
    description: Allow a player to move at normal running speed through water
    default: op
  nocheat.checks.moving.sneaking:
    description: Allow a player to move at normal running speed while sneaking
    default: op
  nocheat.checks.moving.noclip:
    description: Allow a player to walk through walls
    default: op
  nocheat.checks.moving.morepackets:
    description: Allow a player to send more move-event-packets than normal
    default: op

  nocheat.checks.blockbreak.reach:
    description: Allow a player to break blocks at maximum range (about 6-7 blocks)
    default: op
  nocheat.checks.blockbreak.direction:
    description: Allow a player to break blocks that are not in front of them
    default: op
  nocheat.checks.blockbreak.noswing:
    description: Allow a player to use an NoswingCheck hack
    default: op
    
  nocheat.checks.blockplace.reach:
    description: Allow a player to place blocks at maximum range (about 6-7 blocks)
    default: op
  nocheat.checks.blockplace.onliquid:
    description: Allow a player to place non-liquid blocks on liquids
    default: op
  nocheat.checks.blockplace.noswing:
    description: Allow a player to use an NoswingCheck hack
    default: op
    
  nocheat.checks.interact.durability:
    description: Allow a player to use an infinite durability item hack
    default: op
    
  nocheat.checks.fight.direction:
    description: Allow a player to use an direction hack
    default: op
  nocheat.checks.fight.fight:
    description: Allow a player to use an FightCheck hack
    default: op
  nocheat.checks.fight.noswing:
    description: Allow a player to use an NoswingCheck hack
    default: op
  nocheat.checks.fight.selfhit:
    description: Allow a player to use an SelfhitCheck hack
    default: op
    
  nocheat.checks.timed:
    description: Allow a player to use an SelfhitCheck hack
    default: op

  nocheat.admin.*:
    description: Give a player all admin rights
    children:
      nocheat.admin.chatlog: true

  nocheat.admin.chatlog:
    description: Show log messages in the players chat
    default: op
    
  nocheat.*:
    description: Show log messages in the players chat
    default: op
